flowchart TB
N & A;
A <-.->|List of VMs >0?| B;
A ------> C;
C ---> D;
C --->|reboot| E;
E --> F;
F ---->|NIC Enabled| G;
F ---->|NIC Enabled & reboot| H;
H ----> I;
I -.-> B;
G -.-> B;
H ----->|reboot| J;
J --> K;
J -----> L;
L ---> M;
M -.-> B;
K ---> M;
B ---->|no| N;
B ---|yes| C;
D -.-> B;
A(Start Loop)
B{Continue Loop?}
C{Check connection}
D(Connected)
E(Not Connected)
F{Check NIC}
G(Connected)
H(Not Connected)
I[Log]
J{After Nic Check}
M[Log]
L(Connected)
K(Not Connected)
N[Exit Loop]