graph TB
A -.-> B;
A ------> C{C};
C ---> D;
C ---> E;
E --> F{F};
F --> G;
F --> H;
H ----> I;
I -.-> B;
G -.- B;
H -----> J{J};
J --> K;
J --> L;
L --> M;
M -.-> B;
K ---> M;
B ----> N;
B --- C;
D -.-> B;
A(Start)
B{Continue Loop}
C{Check connection}
D(Connected)
E(Not connected)
F{Check NIC}
G(Connected)
H(Not Connected)
I[Log]
J{After Nic Check}
M[Log]
L(Connected)
K(Not Connected)
N[Exit loop]